CREATE TABLE MOVIES (
	idmovie serial PRIMARY KEY,
	title VARCHAR ( 100 ) NOT NULL,
	duration TIME NOT NULL,
	description VARCHAR ( 255 )
)

CREATE TABLE CINEMA_ROOMS (
	idroom serial PRIMARY KEY,
	name VARCHAR ( 100 ) NOT NULL,
	noplaces INTEGER NOT NULL,
	facilities VARCHAR ( 255 )
)

CREATE TABLE REPERTOIRE (
	idRep serial PRIMARY KEY,
	idMovie INTEGER REFERENCES MOVIES (idmovie),
	displayday DATE NOT NULL,
	displaytime TIME NOT NULL,
	idRoom INTEGER REFERENCES CINEMA_ROOMS (idroom),
	noFreeplaces INTEGER,
	ticketPrice REAL
)
CREATE TABLE USERS (
	IdUser serial PRIMARY KEY,
	Login VARCHAR ( 50 ) NOT NULL,
	pass VARCHAR ( 50 ) NOT NULL,
	Email VARCHAR ( 150 ) NULL,
	CreateDate TIMESTAMP NOT NULL,
	group_name VARCHAR ( 15 ) NULL
)
CREATE TABLE RESERVATION (
	IdRes serial PRIMARY KEY,
	IdUser INTEGER REFERENCES USERS (IdUser),
	timestamp TIMESTAMP NOT NULL,
	NoPlaces INTEGER NOT NULL,
	IdRep INTEGER REFERENCES REPERTOIRE (IdRep),
	Cost REAL
)


CREATE TABLE PLACE_RESERVATION (
	IdRes INTEGER REFERENCES RESERVATION (IdRes),
	CountPlace INTEGER NOT NULL,
	Paid VARCHAR NOT NULL
)

CREATE TABLE PLACES (
	IdRoom INTEGER REFERENCES CINEMA_ROOMS (IdRoom),
	NoRow INTEGER NOT NULL,
	NoPlace INTEGER NOT NULL,
	CountPlace INTEGER NOT NULL,
	PRIMARY KEY (IdRoom, CountPlace)
)
